var songs = [
    new Artist("Frank Sinatra", "4fzMwQLxkY6qsimuyaDqed", "frankSinatra.jpg", 1),
    new Artist("Andy Williams", "5hslUAKq9I9CG2bAulFkHN", "andyWilliams.jpg", 2),
    new Artist("Bing Crosby", "6ajihXpsHpDnIdqtBXZYGN", "bingCrosby.jpg", 3),
    new Artist("Josh Groban", "1PPunVEmMEPbLxb3ejHgaB", "joshGroban.jpg", 4),
    new Artist("Perry Como", "5mKxNjNnRFpO9Muzw3Ug0u", "perryComo.jpg", 5),
    new Artist("Nat King Cole", "1l2CvcIAL1MtPbtZhh0Z77", "natKingCole.jpg", 6),
    new Artist("Jack Jones", "4K6gWgQgOgj291NOhM1yqw", "jackJones.png", 7),
    new Artist("Barry Manilow", "6StbRiW6YMTHdA8wj5opCG", "barryManilow.jpg", 8),
    new Artist("Michael Buble", "1FRqLI971CD1QedTiJeL3c", "michaelBuble.jpg", 9),
    new Artist("Justin Bieber", "0E4rAAAzRPE8I7tYzNq99p", "justinBieber.jpg", 10),
    new Artist("Johnny Mathis", "1JtYy7MFUIZM0MREJaZhTP", "johnnyMathis.jpg", 11),
    new Artist("Dean Martin", "3szI9hDVbyOYU0yd77G35n", "deanMartin.jpg", 12),
    new Artist("Harry Connick Jr", "0KWdeiXhPKY3VEY56jA238", "harryConnickJr.jpg", 13),
    new Artist("Tony Bennett", "1NbkW4qACyJ4MDpqP1kAC5", "tonyBennett.png", 14),
    new Artist("Elvis Presley", "3QiAAp20rPC3dcAtKtMaqQ", "elvisPresley.jpg", 15),
    new Artist("Bobby Helms", "7vQbuQcyTflfCIOu3Uzzya", "bobbyHelms.png", 16),
    new Artist("Jerry Vale", "6R69Gl7CaGihbBpNW5utcZ", "jerryVale.jpg", 17),
    new Artist("Toby Keith", "1xmhK20i5Spc261Kvd8XYM", "tobyKeith.jpeg", 18),
    new Artist("Alan Jackson", "70OrTBlb0RLKNfxWE6fZZM", "alanJackson.jpg", 19),
    new Artist("Kenny Rogers", "77lrZDgzDtMZ9nxhofaG2I", "kennyRogers.jpg", 20),
    new Artist("Bobby Vinton", "6mRig6msTgPe8YlTJkrCmy", "bobbyVinton.jpg", 21),
    new Artist("Chuck Berry", "2pnPe4pJtq7689i5ydzvJJ", "chuckBerry.jpg", 22),
    new Artist("Al Martino", "6zMnsAwmH87MTbzq7IIEYD", "alMartino.jpg", 23),
    new Artist("Neil Diamond", "551w3tOvIBhNU49tcak1GZ", "neilDiamond.jpg", 24),
    new Artist("Jim Nabors", "3u4uVvmJaEtwlqMjSMIVKo", "jimNabors.JPG", 25),
    new Artist("Tom Jones", "2BJXVZV3REr0oDvFSD0fnL", "tomJones.jpg", 26),
    new Artist("Gene Autry", "1dtIaSlyrLI04sqYa8nLyN", "geneAutry.jpg", 27),
    new Artist("Vaughn Monroe", "75Sx3XuVfvyOL9k02ylrA0", "vaughnMonroe.jpg", 28),
    new Artist("Englebert Humperdinck", "22qUDZhFd9wQM6f4xDPkQl", "englebertHumperdinck.jpg", 29),
    new Artist("Darius Rucker", "64kvEILhlkdebBdlrtcMJG", "dariusRucker.jpg", 30),
    new Artist("John Denver", "03XY86r29H3R5je3xcdb1X", "johnDenver.jpg", 31),
    new Artist("Burl Ives", "33BcB8XVwJU4qB7bDSkVya", "burlIves.jpg", 32),
    new Artist("---", "", "", "-")
];

var matchups = [
    new Matchup(0, songs[0], songs[31], locations.wintersTX, 16, 1),
    new Matchup(1, songs[15], songs[16], locations.wintersTX, 16, 1),
    new Matchup(2, songs[7], songs[24], locations.hollyMI, 17, 1),
    new Matchup(3, songs[8], songs[23], locations.hollyMI, 17, 1),
    new Matchup(4, songs[3], songs[28], locations.evergreenCO, 18, 1),
    new Matchup(5, songs[12], songs[19], locations.evergreenCO, 18, 1),
    new Matchup(6, songs[4], songs[27], locations.poinsettiaParkFL, 19, 1),
    new Matchup(7, songs[11], songs[20], locations.poinsettiaParkFL, 19, 1),    
    new Matchup(8, songs[1], songs[30], locations.northPoleID, 20, 1),
    new Matchup(9, songs[14], songs[17], locations.northPoleID, 20, 1),
    new Matchup(10, songs[6], songs[25], locations.blitzenOR, 21, 1),
    new Matchup(11, songs[9], songs[22], locations.blitzenOR, 21, 1),
    new Matchup(12, songs[2], songs[29], locations.bethlehemPA, 22, 1),
    new Matchup(13, songs[13], songs[18], locations.bethlehemPA, 22, 1),
    new Matchup(14, songs[5], songs[26], locations.eggnogUT, 23, 1),
    new Matchup(15, songs[10], songs[21], locations.eggnogUT, 23, 1),    
    new Matchup(16, songs[32], songs[32], locations.wintersTX, 24, 2),              
    new Matchup(17, songs[32], songs[32], locations.hollyMI, 24, 2),              
    new Matchup(18, songs[32], songs[32], locations.evergreenCO, 25, 2),              
    new Matchup(19, songs[32], songs[32], locations.poinsettiaParkFL, 25, 2),              
    new Matchup(20, songs[32], songs[32], locations.northPoleID, 26, 2),              
    new Matchup(21, songs[32], songs[32], locations.blitzenOR, 26, 2),              
    new Matchup(22, songs[32], songs[32], locations.bethlehemPA, 27, 2),              
    new Matchup(23, songs[32], songs[32], locations.eggnogUT, 27, 2),              
    new Matchup(24, songs[32], songs[32], locations.santaClausIN, 28, 3),              
    new Matchup(25, songs[32], songs[32], locations.santaClausIN, 28, 3),              
    new Matchup(26, songs[32], songs[32], locations.antlersOK, 29, 3),              
    new Matchup(27, songs[32], songs[32], locations.antlersOK, 29, 3),              
    new Matchup(28, songs[32], songs[32], locations.santaClausIN, 30, 4),              
    new Matchup(29, songs[32], songs[32], locations.antlersOK, 30, 4),              
    new Matchup(30, songs[32], songs[32], locations.christmasCoveME, null, 5)
]

var bestMaleSinger = new Game(0,"Best Male Singer", songs, matchups, "bestMaleSinger.js", false);
