var songs = [
    new Artist("All I Want for Christmas is You", '0bYg9bo50gSsH3LtXe2SQn', 'mariahCarey.jpg', 1),
    new Artist("Santa Tell Me", '0lizgQ7Qw35od7CYaoMBZb', 'ariana_grande.webp', 2),
    new Artist("Mistletoe", '7xapw9Oy21WpfEcib2ErSA', 'justin_bieber_christmas.jpg', 3),
    new Artist("Underneath the Tree", '2mQeI6pqrBgBvBvqyOgXcN', 'kellyClarkson.jpg', 4),
    new Artist("My Only Wish (This Year)", '0YWUHZPJVg4iujddsJDwhM', 'britneySpears.jpg', 5),
    new Artist("You Make it Feel Like Christmas", '2OQ6a4CfUeYskpTTgyawyJ', 'blake-shelton-gwen-stefani-christmas-in-rockefeller.jpg', 6),
    new Artist("Merry Christmas, Happy Holiday", '4v9WbaxW8HdjqfUiWYWsII', 'nsync.jpg', 7),
    new Artist("All I Want for Christmas Is You", '1FRqLI971CD1QedTiJeL3c', 'michaelbuble.jpg', 8),
    new Artist("Christmas Tree Farm", '2mvabkN1i2gLnGAPUVdwek', 'taylorswift.jpg', 9),
    new Artist("Candy Cane Lane", '4KevTcBXEIYxXVyPE78XXm', 'sia.jpg', 10),
    new Artist("Happy Xmas", '5KHzV8Gf3aweIMImliFAOs', 'miley-cyrus-mark-ronson.jpg', 11),
    new Artist("Rockin' Around The Christmas Tree", '0eLrZL1SJRqgN7iQZGY8Js', 'ingridmichaelson.webp', 12),
    new Artist("Sleigh Ride", '0kIVSKPygLNAEBi7EVeeJn', 'fun.jpg', 13),
    new Artist("Baby, It's Cold Outside", '3xvFTqHmlMqKjHgczCGn2C', 'lydia_liza_joseph_lemanski.jpg', 14),
    new Artist("God Rest Ye Merry Gentlemen", '6eou298JmAGYShrwYuLxJ2', 'bnl_sarah.webp', 15),
    new Artist("The Christmas Shoes", '2P950p6RQQxCROYYZGjcBr', 'christmas_shoes.jpg', 16),
    new Artist("Jingle Bells", '2kvXnUbRUnHS5195eyQp4a', 'laurenDaigle.jpg', 17),
    new Artist("River", '3yLCQ4GRSFlg3GmwlYQlzX', 'sarahMcLachlan.jpg', 18),
    new Artist("We Wish You a Merry Christmas", '1swm2Hei9tUlcohs0zj7DU', 'weezer.jpg', 19),
    new Artist("Christmas Wrapping", '1O2ymfIOPUz7RLzjDCnCWv', 'spicegirls.jpg', 20),
    new Artist("It's the Most Wonderful Time of the Year", '1j51n0VAlLbbHWLHDAX2Ts', 'brett_eldredge.jpg', 21),
    new Artist("It Came Upon a Midnight Clear", '040PVy5Qjz6z4IAvsLbXbn', 'josh_groban.jpg', 22),
    new Artist("Last Christmas", '5ryjlKuQ1J5cACtZ7BdZ9z', 'meghan-trainor.jpg', 23),
    new Artist("Silent Night", '3WP3OIYgTAnfFuiQBvgzgi', 'boyz_II_men.jpg', 24),
    new Artist("It's Begining to Look a Lot Like Christmas", '70y9Vle659GH7TI0w6RraH', 'harry_connick_jr.jpg', 25),
    new Artist("What Are You Doing New Year's Eve?", '0SZim5k1ypcgRsWmFcrGfs', 'the_head_and_the_heart.jpg', 26),
    new Artist("Mele Kalikimaka", '0aVZwOMLntqrkth0DBo5An', 'jimmy_buffet.jpg', 27),
    new Artist("Silver Bells", '1cvLCD35IsBkJ9QuufIrXK', 'lady_a.webp', 28),
    new Artist("Happy Holiday", '3D480qIxLMA5uUC87cfhc0', 'she_and_him.jpg', 29),
    new Artist("White Christmas", '4j5ybw5yYBVKnyN9Ei0DF8', 'norah_jones.jpg', 30),
    new Artist("Have Yourself a Merry Little Christmas", '7us9KL6g1bLBAoUSVu7Qzb', 'kacey_musgraves.jpg', 31),
    new Artist("Run Run Rudolph", '5q54Y9ZR4F0Nh8F83IJB9l', 'foo_fighters.jpg', 32),
    new Artist("---", "", "", "-")
];


var matchups = [
    new Matchup(0, songs[0], songs[31], null, 16, 1),
    new Matchup(1, songs[15], songs[16], null, 16, 1),
    new Matchup(2, songs[7], songs[24], null, 17, 1),
    new Matchup(3, songs[8], songs[23], null, 17, 1),
    new Matchup(4, songs[3], songs[28], null, 18, 1),
    new Matchup(5, songs[12], songs[19], null, 18, 1),
    new Matchup(6, songs[4], songs[27], null, 19, 1),
    new Matchup(7, songs[11], songs[20], null, 19, 1),    
    new Matchup(8, songs[1], songs[30], null, 20, 1),
    new Matchup(9, songs[14], songs[17], null, 20, 1),
    new Matchup(10, songs[6], songs[25], null, 21, 1),
    new Matchup(11, songs[9], songs[22], null, 21, 1),
    new Matchup(12, songs[2], songs[29], null, 22, 1),
    new Matchup(13, songs[13], songs[18], null, 22, 1),
    new Matchup(14, songs[5], songs[26], null, 23, 1),
    new Matchup(15, songs[10], songs[21], null, 23, 1),    
    new Matchup(16, songs[32], songs[32], null, 24, 2),              
    new Matchup(17, songs[32], songs[32], null, 24, 2),              
    new Matchup(18, songs[32], songs[32], null, 25, 2),              
    new Matchup(19, songs[32], songs[32], null, 25, 2),              
    new Matchup(20, songs[32], songs[32], null, 26, 2),              
    new Matchup(21, songs[32], songs[32], null, 26, 2),              
    new Matchup(22, songs[32], songs[32], null, 27, 2),              
    new Matchup(23, songs[32], songs[32], null, 27, 2),              
    new Matchup(24, songs[32], songs[32], null, 28, 3),              
    new Matchup(25, songs[32], songs[32], null, 28, 3),              
    new Matchup(26, songs[32], songs[32], null, 29, 3),              
    new Matchup(27, songs[32], songs[32], null, 29, 3),              
    new Matchup(28, songs[32], songs[32], null, 30, 4),              
    new Matchup(29, songs[32], songs[32], null, 30, 4),              
    new Matchup(30, songs[32], songs[32], null, null, 5)
]

var bestContemporarySong = new Game(4, "[NEW] Best Contemporary Christmas Song", songs, matchups, "bestContemporarySong.js", false);
